version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html/nodeapp

permissions:
  - object: /var/www/html/nodeapp
    pattern: "**"
    owner: ubuntu
    group: www-data

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: deploy.sh
      timeout: 300
      runas: ubuntu
