version: 0.0
os: linux
 
files:
  - source: /
    destination: /var/www/html
 
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755
 
hooks:
  AfterInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu
 
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 300
      runas: ubuntu
